package com.example.zydemo.controller;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * 页面controller, 按需改名
 * generated by hik-ga-archetype-webapp
 * 
 * @author 
 */
@Api("测试Controller")
@Controller
public class TestController {
  
  @RequestMapping(value = "/index", method = {RequestMethod.GET})
  public String index() {
    return "index";
  }

  @ApiOperation(value = "测试")
  @RequestMapping(value = "/getString", method = {RequestMethod.GET})
  @ResponseBody
  public String getString() {
    return "success";
  }
  
}